name: Generate Snake


on:
schedule:
- cron: "0 0 * * *" # jalan tiap hari 00:00 UTC
workflow_dispatch: # bisa dijalankan manual
push:
branches: ["main"] # update saat ada push ke main


jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Generate snake SVG
uses: Platane/snk@v3
with:
github_user_name: evan # ganti jika username kamu beda
outputs: |
dist/snake.svg


- name: Upload artifact (opsional)
uses: actions/upload-artifact@v4
with:
name: snake
path: dist/snake.svg


- name: Push to output branch
if: ${{ github.ref == 'refs/heads/main' }}
uses: crazy-max/ghaction-github-pages@v4
with:
target_branch: output
build_dir: dist
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
